import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ashish NextJS",
  description: "Generated by Ashish Panwar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-600 text-center p-6">Header</header>
        <main className="p-4 text-center p-4">
          {children}
        </main>
        <footer className="bg-gray-600 text-center p-6">Footer</footer>
      </body>
    </html>
  );
}
